name: pre-commit

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [ '**' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'main'}}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.*
      - name: Install pycodestyle
        run: pip install pycodestyle==2.5.0
      - name: Lint backend
        run: pycodestyle . --ignore=E501,E742,W504,W503 --exclude=migrations
